#!/bin/bash

echo "=== Método alternativo para fazer push no GitHub ==="
echo ""
echo "1. Primeiro, crie um Personal Access Token no GitHub:"
echo "   - Acesse: https://github.com/settings/tokens/new"
echo "   - Nome: 'CrypTalk Push Token'"
echo "   - Expiração: 30 dias (ou sua preferência)"
echo "   - Selecione os escopos:"
echo "     ✓ repo (todos os sub-itens)"
echo "     ✓ workflow"
echo "   - Clique em 'Generate token'"
echo "   - COPIE O TOKEN (só aparece uma vez!)"
echo ""
echo "2. Configure o Git com suas credenciais:"
echo "   git config --global user.name 'Seu Nome'"
echo "   git config --global user.email 'surgical.brasil@gmail.com'"
echo ""
echo "3. Adicione o remote do repositório:"
echo "   git remote add origin https://github.com/SEU-USUARIO/cryptalk.git"
echo ""
echo "4. Faça o push usando o token:"
echo "   git push -u origin main"
echo "   # Quando pedir username: coloque seu username do GitHub"
echo "   # Quando pedir password: cole o TOKEN (não sua senha do GitHub)"
echo ""
echo "=== Alternativa: Usar SSH ==="
echo "Se preferir usar SSH:"
echo "1. Gere uma chave SSH (se não tiver):"
echo "   ssh-keygen -t ed25519 -C 'surgical.brasil@gmail.com'"
echo ""
echo "2. Adicione a chave ao GitHub:"
echo "   cat ~/.ssh/id_ed25519.pub"
echo "   # Copie o conteúdo e adicione em: https://github.com/settings/keys"
echo ""
echo "3. Configure o remote com SSH:"
echo "   git remote add origin git@github.com:SEU-USUARIO/cryptalk.git"
echo "   git push -u origin main"