#!/bin/bash

echo "=== Método com Personal Access Token ==="
echo ""
echo "1. Crie um token em: https://github.com/settings/tokens/new"
echo "   - Marque: repo, workflow"
echo "   - Gere e COPIE o token"
echo ""
echo "2. Execute este comando substituindo os valores:"
echo ""
echo "export GITHUB_TOKEN='SEU_TOKEN_AQUI'"
echo "export GITHUB_USER='SEU_USUARIO'"
echo ""
echo "git remote add origin https://\$GITHUB_USER:\$GITHUB_TOKEN@github.com/\$GITHUB_USER/cryptalk.git"
echo "git push -u origin main"
echo ""
echo "=== Exemplo: ==="
echo "export GITHUB_TOKEN='ghp_xxxxxxxxxxxxxxxxxx'"
echo "export GITHUB_USER='surgical'"
echo "git remote add origin https://\$GITHUB_USER:\$GITHUB_TOKEN@github.com/\$GITHUB_USER/cryptalk.git"
echo "git push -u origin main"