#!/bin/bash

echo "=== Instalando GitHub CLI ==="
echo "Execute os seguintes comandos:"
echo ""
echo "# 1. Instalar GitHub CLI"
echo "sudo apt update"
echo "sudo apt install gh"
echo ""
echo "# 2. Fazer login no GitHub"
echo "gh auth login"
echo "# Escolha: GitHub.com > HTTPS > Login with web browser"
echo ""
echo "# 3. Criar repositório e fazer push"
echo "cd /home/surgical/my-claude-project/CrypTalk"
echo "gh repo create cryptalk --public --description 'Secure messaging application with end-to-end encryption' --source=. --remote=origin --push"
echo ""
echo "=== Alternativa se o gh repo create falhar ==="
echo "# Criar apenas o repositório:"
echo "gh repo create cryptalk --public --description 'Secure messaging application with end-to-end encryption'"
echo ""
echo "# Adicionar remote e fazer push manualmente:"
echo "git remote add origin https://github.com/SEU-USUARIO/cryptalk.git"
echo "git push -u origin main"